### ISSUE TITLE
PTM crash

### ISSUE THREAD

**Issue by bentsi** [Microsoft/WindowsProtocolTestSuites#118]
PTM crashed during execution of all tests of the FileServer test suite against Samba cluster.
Exception was: System.UnhandledExceptionEventArgs
![image](https://user-images.githubusercontent.com/5269241/28753078-f4df71ac-7536-11e7-8c82-04a9175b8768.png)

WindowsProtocolTestSuites 2.0

**Comment by JiajunW** [comment]
Thanks for reporting. I will look into this issue.

**Comment by bentsi** [comment]
```
Platform: NonWindows
MaxSmbVersionSupported: Smb302
' (c of ReadConfig, state S644; expected value originates from previous binding)
2017-08-20 14:29:17.571 [CheckSucceeded] Assert.IsTrue succeeded. expected 'OplockConfig State:
Platform: NonWindows
MaxSmbVersionSupported: Smb302
', actual 'OplockConfig State:
Platform: NonWindows
MaxSmbVersionSupported: Smb302
' (v == c; values originate from previous binding)
2017-08-20 14:29:17.571 [CheckSucceeded] Assert.IsTrue succeeded. Fail to check the assumption : v.MaxSmbVersionSupported == 770
2017-08-20 14:29:17.571 [Comment] reaching state 'S645'
2017-08-20 14:29:17.571 [Comment] executing step 'call SetupConnection(Smb2002,NO_SMB2_SHAREFLAG_FORCE_LEVELII_OPLOCK,NO_STYPE_CLUSTER_SOFS)'
2017-08-20 14:29:17.571 [CheckInconclusive] Assert.Inconclusive is inconclusive. The value of ShareWithoutForceLevel2OrSOFS is empty.
2017-08-20 14:29:17.572 [Comment]    at Microsoft.Protocols.TestSuites.FileSharing.Common.Adapter.TestConfigBase.GetProperty(String groupName, String propertyName, Boolean checkNullOrEmpty) in e:\Jenkins\workspace\CodeSign-TestSuites\TestSuite\TestSuites\FileServer\src\Common\Adapter\TestConfigBase.cs:line 471

2017-08-20 14:29:17.572 [Debug] Microsoft.VisualStudio.TestTools.UnitTesting.AssertInconclusiveException: Assert.Inconclusive is inconclusive. The value of ShareWithoutForceLevel2OrSOFS is empty.
===== Stack Trace =====
   at Microsoft.Protocols.TestSuites.FileSharing.Common.Adapter.TestConfigBase.GetProperty(String groupName, String propertyName, Boolean checkNullOrEmpty) in e:\Jenkins\workspace\CodeSign-TestSuites\TestSuite\TestSuites\FileServer\src\Common\Adapter\TestConfigBase.cs:line 471
=== End of Stack Trace ===

   at Microsoft.Protocols.TestTools.AsynchronousErrorProcessor.Process()
   at Microsoft.Protocols.TestTools.AsynchronousErrorProcessor.ReportAsyncException(Exception checkerException)
   at Microsoft.Protocols.TestTools.Checking.DefaultChecker`2.GenerateException(CheckResult checkResult, String message, Object[] parameters)
   at Microsoft.Protocols.TestTools.Checking.DefaultChecker`2.Inconclusive(String message, Object[] parameters)
   at Microsoft.Protocols.TestSuites.FileSharing.Common.Adapter.TestConfigBase.GetProperty(String groupName, String propertyName, Boolean checkNullOrEmpty) in e:\Jenkins\workspace\CodeSign-TestSuites\TestSuite\TestSuites\FileServer\src\Common\Adapter\TestConfigBase.cs:line 471
   at Microsoft.Protocols.TestSuites.FileSharing.SMB2Model.Adapter.SMB2ModelTestConfig.GetProperty(String propertyName, Boolean checkNullOrEmpty) in e:\Jenkins\workspace\CodeSign-TestSuites\TestSuite\TestSuites\FileServer\src\SMB2Model\Adapter\SMB2ModelTestConfig.cs:line 23
   at Microsoft.Protocols.TestSuites.FileSharing.SMB2Model.Adapter.SMB2ModelTestConfig.get_ShareWithoutForceLevel2OrSOFS() in e:\Jenkins\workspace\CodeSign-TestSuites\TestSuite\TestSuites\FileServer\src\SMB2Model\Adapter\SMB2ModelTestConfig.cs:line 35
   at Microsoft.Protocols.TestSuites.FileSharing.SMB2Model.Adapter.Oplock.OplockAdapter.SetupConnection(ModelDialectRevision maxSmbVersionClientSupported, ModelShareFlag shareFlag, ModelShareType shareType) in e:\Jenkins\workspace\CodeSign-TestSuites\TestSuite\TestSuites\FileServer\src\SMB2Model\Adapter\Oplock\OplockAdapter.cs:line 106
2017-08-20 14:29:17.573 [TestInconclusive] Microsoft.Protocols.TestSuites.FileSharing.SMB2Model.TestSuite.OplockOnShareWithoutForceLevel2OrSOFSTestCase.OplockOnShareWithoutForceLevel2OrSOFSTestCaseS643
2017-08-20 14:29:17.641 [Comment] reaching state 'S432'
```

**Comment by JiajunW** [comment]
I think the reason why this case is inconclusive is `ShareWithoutForceLevel2OrSOFS` in `MS-SMB2Model_ServerTestSuite.deployment.ptfconfig` is empty.

BTW, does this cause the very first unexpected error as shown in your first screenshot?

**Comment by JiajunW** [comment]
Close the issue since no response for a long time.

Feel free to reopen it or raise a new issue if it still does not work.
