### ISSUE TITLE
RDP client tests failed with error "The credentials supplied to the package were not recognized"

### ISSUE THREAD

**Issue by ligurio** [microsoft/WindowsProtocolTestSuites#183]
I'm running tests against RDP client and most part of tests failed with error "The credentials supplied to the package were not recognized".

As far as I understand correctly error is connected to wrong certificate used by RDP server.
Path to certificate is correct, password used in certificate is correct too. What can be wrong?

**Microsoft Protocol Test Manager** 24.0.5.2019
**Windows Protocol Test Framework** 24.0.5.2019
**Microsoft RDP Client Endpoint TestSuite** 27.05.2019
**Microsoft RDP Server Endpoint TestSuite** 23.05.2019

Thanks in advance.

```
2019-07-03 18:57:06.656 [Comment] Expected execution time of the test suite (in
seconds) is:
2019-07-03 18:57:06.726 [Comment] Adapter Microsoft.Protocols.TestSuites.Rdpbcgr
.RdpbcgrAdapter implements Microsoft.Protocols.TestSuites.Rdpbcgr.IRdpbcgrAdapte
r
2019-07-03 18:57:06.729 [Comment] Adapter Microsoft.Protocols.TestSuites.Rdp.Pro
tocolBasedRdpSUTControlAdapter implements Microsoft.Protocols.TestSuites.Rdp.IRd
pSutControlAdapter
2019-07-03 18:57:06.750 [Debug] isClientSupportFastPathInput = True;
                isClientSuportAutoReconnect = False;
                isClientSupportRDPEFS = False;
                isClientSupportServerRedirection = False;
                isClientSupportEmptyRdpNegData = False;
                isClientSupportSoftSync = True
                isClientSupportTunnelingStaticVCTraffic = True
2019-07-03 18:57:06.754 [Comment] Starting RDP listening.
2019-07-03 18:57:06.843 [Debug] The IP version is Ipv4.
2019-07-03 18:57:06.844 [Debug] RDP server is listening on 0.0.0.0:3389.
2019-07-03 18:57:06.844 [Comment] Triggering SUT to initiate a RDP connection to
 server.
2019-07-03 18:57:06.850 [Comment] RDP SUT Control Protocol Adapter: CommandId is
 1: Success, agent: 10.16.171.18:4488.
2019-07-03 18:57:06.850 [Comment] Expecting the transport layer connection reque
st.
2019-07-03 18:57:06.961 [Debug] A RDP client initiates a connection. The local e
ndpoint is 10.16.170.5:3389. The remote endpoint is 10.16.171.18:53930
2019-07-03 18:57:06.961 [Comment] Establishing RDP connection.
2019-07-03 18:57:06.963 [Comment] EstablishRDPConnection(
                Selected Protocol = PROTOCOL_SSL_FLAG,
                Encyrption Method = ENCRYPTION_METHOD_NONE,
                Encyrption Level = ENCRYPTION_LEVEL_NONE,
                Extended Client Data Supported = True,
                Auto-Reconnection Expected = False,
                RDP Version Code= V2).
2019-07-03 18:57:06.967 [Debug] CheckX224ConnectionRequestPdu
2019-07-03 18:57:06.985 [Debug] System.ComponentModel.Win32Exception (0x80004005): The credentials supplied to the package were not recognized at System.Net.SSPIWrapper.AcquireCredentialsHandle(SSPIInterface SecModule, String package, CredentialUse intent, SecureCredential scc)
at System.Net.Security.SecureChannel.AcquireCredentialsHandle(CredentialUse credUsage, SecureCredential& secureCredential) at System.Net.Security.SecureChannel.AcquireServerCredentials(Byte[]& thumbPrint)
at System.Net.Security.SecureChannel.GenerateToken(Byte[] input, Int32 offset, Int32 count, Byte[]& output)
at System.Net.Security.SecureChannel.NextMessage(Byte[] incoming, Int32 offset, Int32 count)
at System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
at System.Net.Security.SslState.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
at System.Net.Security.SslState.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
at System.Net.Security.SslState.StartReceiveBlob(Byte[] buffer, AsyncProtocol Request asyncRequest)
at System.Net.Security.SslState.ForceAuthentication(Boolean receiveFirst, Byte[] buffer, AsyncProtocolRequest asyncRequest)at System.Net.Security.SslState.ProcessAuthentication(LazyAsyncResult lazyResult)
at System.Net.Security.SslStream.AuthenticateAsServer(X509Certificate serverCertificate, Boolean clientCertificateRequired, SslProtocols enabledSslProtocols, Boolean checkCertificateRevocation)
at System.Net.Security.SslStream.AuthenticateAsServer(X509Certificate serverCertificate)
at Microsoft.Protocols.TestTools.StackSdk.RemoteDesktop.Rdpbcgr.RdpbcgrServer TransportStack.UpdateConfig(SecurityStreamType type) in C:\Jenkins\workspace\ESRPCodeSign-TestSuite-withRegression-Pipeline\build\ProtoSDK\MS-RDPBCGR\Server\RdpbcgrServerTransportStack.cs:line 727
at Microsoft.Protocols.TestTools.StackSdk.RemoteDesktop.Rdpbcgr.RdpbcgrServer.UpdateTransport() in C:\Jenkins\workspace\ESRPCodeSign-TestSuite-withRegression-Pipeline\build\ProtoSDK\MS-RDPBCGR\Server\RdpbcgrServer.cs:line 4484
at Microsoft.Protocols.TestTools.StackSdk.RemoteDesktop.Rdpbcgr.RdpbcgrServer.SendPdu(RdpbcgrServerSessionContext sessionContext, RdpbcgrServerPdu pdu) in C:\Jenkins\workspace\ESRPCodeSign-TestSuite-withRegression-Pipeline\build\ProtoSDK\MS-RDPBCGR\Server\RdpbcgrServer.cs:line 490
at Microsoft.Protocols.TestSuites.Rdpbcgr.RdpbcgrAdapter.Server_X_224_Connection_Confirm(selectedProtocols_Values protocol, RDP_NEG_RSP_flags_Values flags) in C:\Jenkins\workspace\ESRPCodeSign-TestSuite-withRegression-Pipeline\build\TestSuites\RDP\Client\src\Adapter\RDPBCGR\RdpbcgrAdapter.cs:line 417
at Microsoft.Protocols.TestSuites.Rdpbcgr.RdpbcgrAdapter.EstablishRDPConnection(selectedProtocols_Values serverSelectedProtocol, EncryptionMethods enMethod, EncryptionLevel enLevel, Boolean isExtendedClientDataSupported, Boolean expectAutoReconnect, TS_UD_SC_CORE_version_Values rdpServerVersion, MULTITRANSPORT_TYPE_FLAGS multiTransportTypeFlags, Boolean supportRDPEGFX, Boolean supportRestrictedAdminMode) in C:\Jenkins\workspace\ESRPCodeSign-TestSuite-withRegression-Pipeline\build\TestSuites\RDP\Client\src\Adapter\RDPBCGR\RdpbcgrAdapter_Sequences.cs:line 822019-07-03 18:57:07.010 [Comment] Trigger client to close all RDP connections for clean up.
```

**Comment by huiren-jiang** [comment]
Hi Sergey,

Could you please give us more detail about how you generate the certificate used by RDPClient test suites?

This certificate is actually used to do server side TLS authentication. This self signed certificate in .pfx together with the password could be generated by below code snippet from [Config-DriverComputer.ps1](https://github.com/microsoft/WindowsProtocolTestSuites/blob/staging/TestSuites/RDP/Client/Setup/Scripts/Config-DriverComputer.ps1)

$cert = New-SelfSignedCertificate -DnsName $certCN -CertStoreLocation "cert:\LocalMachine\My"

$securePwd = (ConvertTo-SecureString -string "$certPwd" -Force -AsPlainText)

Export-PfxCertificate -Cert $cert -Force -Password $securePwd -FilePath "$env:HOMEDRIVE\$certFileName.pfx"

Would you please also try these PowerShell commands to re-generate the test certificate?

Thanks,

Windows Protocol Test Suites Development Team

**Comment by ligurio** [comment]
Hi, Huiren Jiang

I'm using openssl for certificate generation:
```
openssl req -x509 -newkey rsa:4096 -keyout key.pem -out cert.pem -days 365
openssl pkcs12 -export -out cert.pfx -inkey key.pem -in cert.pem -certfile cert.pem
```
```cert.pfx``` is a certificate which I use with Protocol Test Manager.

> Would you please also try these PowerShell commands to re-generate the test certificate?

I'll try and report here about results.

**Comment by ligurio** [comment]
script `.\Config-DriverComputer.ps1` failed with certificate generation:

```
Create a self-signed certificate and export it out...
New-SelfSignedCertificate : The term 'New-SelfSignedCertificate' is not recognized as the name of a cmdlet, function, s
cript file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is cor
rect and try again.
At C:\MicrosoftProtocolTests\RDP\Client-Endpoint\3.19.3.0\Scripts\Config-DriverComputer.ps1:146 char:1
+ New-SelfSignedCertificate -DnsName $certCN -CertStoreLocation "cert:\LocalMachin ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (New-SelfSignedCertificate:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

Export-PfxCertificate : The term 'Export-PfxCertificate' is not recognized as the name of a cmdlet, function, script fi
le, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and
 try again.
At C:\MicrosoftProtocolTests\RDP\Client-Endpoint\3.19.3.0\Scripts\Config-DriverComputer.ps1:149 char:1
+ Export-PfxCertificate -Cert $cert -Force -Password $securePwd -FilePath "$env:HO ...
+ ~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Export-PfxCertificate:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

Export-Certificate : The term 'Export-Certificate' is not recognized as the name of a cmdlet, function, script file, or
 operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try a
gain.
At C:\MicrosoftProtocolTests\RDP\Client-Endpoint\3.19.3.0\Scripts\Config-DriverComputer.ps1:150 char:1
+ Export-Certificate -Cert $cert -FilePath "$env:HOMEDRIVE\$certFileName.cer" -Typ ...
+ ~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Export-Certificate:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
```

**OS version:** Windows 7 x86_64

**Comment by ligurio** [comment]
In [Client RDP User Guide](https://github.com/microsoft/WindowsProtocolTestSuites/blob/staging/TestSuites/RDP/Client/docs/RDP_ClientUserGuide.md#requirements) driver computer has following requirements: any Windows version supported by Visual Studio 2017. I have Windows 7 SP1 x86_64 with latest updates, it is supported by VS2017 according [official site](https://docs.microsoft.com/en-us/visualstudio/productinfo/vs2017-system-requirements-vs). Why script `.\Config-DriverComputer.ps1` failed?

**Comment by huiren-jiang** [comment]
Hi Sergey,

Config-DriverComputer.ps1 failed due to those PowerShell commands related to operating certificate require Windows 8/Windows Server 2012. If you have access to newer Windows version, you could try to generate the pfx file with those commands then copy it to your test machine installed Windows 7.

Also, we are investigating how to generate a usable test certificate using OpenSSL.

Thanks,

Windows Protocol Test Suites Development Team

**Comment by huiren-jiang** [comment]
Hi Sergey,

We managed to use OpenSSL to create a usable certificate for RDP testing. Could you please also try below commands?

```
openssl req -x509 -newkey rsa:4096 -keyout key.pem -out cert.crt -days 365
openssl pkcs12 -export -out cert.pfx -inkey key.pem -in cert.crt
```

Thanks,

Windows Protocol Test Suites Development Team

**Comment by ligurio** [comment]
Problem resolved by generation certificate using `Config-DriverComputer.ps1` under Windows 10.

> We managed to use OpenSSL to create a usable certificate for RDP testing. Could you please also try below commands?

I'll check it.

**Comment by ligurio** [comment]
> We managed to use OpenSSL to create a usable certificate for RDP testing. Could you please also try below commands?

Certificates generated using OpenSSL works fine. Thanks!
