### ISSUE TITLE
File Server Family Test Suite fails with error “QTAgent.exe has stopped working”

### ISSUE THREAD

**Issue by shishir-compuverde** [Microsoft/WindowsProtocolTestSuites#91]
Hi,
I tried to run File Server Family Test Suite against Windows Server 2016 and it failed with error “QTAgent.exe has stopped working”. I used the following configuration –

**\- Client01**
OS Name:        Microsoft Windows 10 Enterprise Evaluation
OS Version:     10.0.14393 N/A Build 14393
OS Manufacturer:    Microsoft Corporation
OS Configuration:   Member Workstation
OS Build Type:      Multiprocessor Free

_Client01 Software:_
VisualStudio 2012 Premium Update 5
Spec Explorer (version 3.5.3146.0)
Protocol Test Framework (version 1.0.5000.0)
File Server Test Suite (version 1.0.5142.0)
Protocol Test Manager (version 1.0.5142.0)

**\- DC01, Node01, Node02, Storage01**
OS Name:        Microsoft Windows Server 2016 Standard Evaluation
OS Version:     10.0.14393 N/A Build 14393
OS Manufacturer:    Microsoft Corporation
OS Configuration:   Member Server
OS Build Type:      Multiprocessor Free

_// The VM configuration applies to all VMs_
Machine type:   VM
Hypervisor: ESXi 6.0 U2
vCPU:   2
RAM:    2GB
Disk:   64GB

Please find the attached screenshots of the error.
Also, please let me know if you require more information regarding the error.

![protocoltestmanager crash](https://cloud.githubusercontent.com/assets/22982616/19602496/bdeff1e2-97ad-11e6-8a8e-a50f746d1463.PNG)
![qtagent crash](https://cloud.githubusercontent.com/assets/22982616/19602495/bdefe242-97ad-11e6-8af9-a23e45f37b59.PNG)

/Shishir

**Comment by JessieF** [comment]
Hi Shishir,

Could you debug the Protocol Test Manager in your environment and send back the debug trace to us? You could send us a snapshot of the exception in Visual Studio, then we could know which line throw it.

- Open "ProtocolTestManager/ProtocolTestManager.sln" in VS
    

- Set UI project as StartUp Project

- Change 'installDir' in 'ProtocolTestManager\Kernel\Utility.cs' to the install folder of Protocol Test Manger, such as "C:\Program Files (x86)\Protocol Test Manager".

Now you could click 'Start' button in VS, then use this debugging protocol test manager to repro the issue you met.

Thanks.
/Jessie

**Comment by shishir-compuverde** [comment]
Hi Jessie,
Thanks a lot for your reply. I’ve attached some debug traces in Visual Studio about the error.
Please have a look on them and let me know whether you require any further information.

![vs qtagent crash1](https://cloud.githubusercontent.com/assets/22982616/19644275/21d551e6-99ef-11e6-8d60-351612e26dfe.PNG)

**System.TimeoutException was unhandled**
  HResult=-2146233083
  Message=The operation has timed out.
  Source=Microsoft.Protocols.TestTools.StackSdk.FileAccessService.Smb2

  **_StackTrace:_**
       at Microsoft.Protocols.TestTools.StackSdk.FileAccessService.Smb2.ReceivedPackets.WaitPacket(UInt64 messageId) in c:\Users\administrator.TESTSUITE2\Desktop\Softwares\WindowsProtocolTestSuites-staging\ProtoSDK\MS-SMB2\Client\Smb2Client.cs:line 117
       at Microsoft.Protocols.TestTools.StackSdk.FileAccessService.Smb2.Smb2Client.ExpectPacket[T](UInt64 messageId) in c:\Users\administrator.TESTSUITE2\Desktop\Softwares\WindowsProtocolTestSuites-staging\ProtoSDK\MS-SMB2\Client\Smb2Client.cs:line 569
       at Microsoft.Protocols.TestTools.StackSdk.FileAccessService.Smb2.Smb2Client.SendPacketAndExpectResponse[T](Smb2Packet packet) in c:\Users\administrator.TESTSUITE2\Desktop\Softwares\WindowsProtocolTestSuites-staging\ProtoSDK\MS-SMB2\Client\Smb2Client.cs:line 521
       at Microsoft.Protocols.TestTools.StackSdk.FileAccessService.Smb2.Smb2Client.TreeDisconnect(UInt16 creditCharge, UInt16 creditRequest, Packet_Header_Flags_Values flags, UInt64 messageId, UInt64 sessionId, UInt32 treeId, Packet_Header& responseHeader, TREE_DISCONNECT_Response& responsePayload, UInt16 channelSequence) in c:\Users\administrator.TESTSUITE2\Desktop\Softwares\WindowsProtocolTestSuites-staging\ProtoSDK\MS-SMB2\Client\Smb2Client.cs:line 1220
       at Microsoft.Protocols.TestSuites.FileSharing.FSA.Adapter.Smb2TransportAdapter.TreeDisconnect() in c:\Users\administrator.TESTSUITE2\Desktop\Softwares\WindowsProtocolTestSuites-staging\TestSuites\FileServer\src\FSA\Adapter\Smb3TransportAdapter.cs:line 418
       at Microsoft.Protocols.TestSuites.FileSharing.FSA.Adapter.Smb2TransportAdapter.Dispose(Boolean disposing) in c:\Users\administrator.TESTSUITE2\Desktop\Softwares\WindowsProtocolTestSuites-staging\TestSuites\FileServer\src\FSA\Adapter\Smb3TransportAdapter.cs:line 240
       at Microsoft.Protocols.TestTools.ManagedAdapterBase.Finalize()
  InnerException: 


![vs qtagent crash2](https://cloud.githubusercontent.com/assets/22982616/19644337/5fef80fa-99ef-11e6-8d55-3118f0cd3e67.PNG)

**System.InvalidOperationException was unhandled**
  HResult=-2146233079
  Message=Collection was modified; enumeration operation may not execute.
  Source=mscorlib

  **_StackTrace:_**
       at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
       at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
       at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
       at Microsoft.Protocols.TestManager.Kernel.GroupByOutcome.ChangeStatus(String testCaseName, TestCaseStatus status) in c:\Users\administrator.TESTSUITE2\Desktop\Softwares\WindowsProtocolTestSuites-staging\ProtocolTestManager\Kernel\TestEngine\GroupByOutcome.cs:line 92
       at Microsoft.Protocols.TestManager.Kernel.TestEngine.ParseLogMessage(String message) in c:\Users\administrator.TESTSUITE2\Desktop\Softwares\WindowsProtocolTestSuites-staging\ProtocolTestManager\Kernel\TestEngine\TestEngine.cs:line 205
       at Microsoft.Protocols.TestManager.Kernel.Listener.Run() in c:\Users\administrator.TESTSUITE2\Desktop\Softwares\WindowsProtocolTestSuites-staging\ProtocolTestManager\Kernel\TestEngine\PipeSinkServer.cs:line 117
       at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
       at System.Threading.ThreadHelper.ThreadStart()
  InnerException: 


Thanks.
/Shishir

**Comment by yazeng** [comment]
Hi Shishir,
Thank you for the quick response and also the awesome debug trace!
I think there're two bugs. One is in test suite, the other is in PTM.
For the first one, the QTAgent crash, I had some thoughts.
Could you open the file below,
![snip_20161025111327](https://cloud.githubusercontent.com/assets/10937464/19671818/182c28a8-9aa4-11e6-8be1-e932173d3b3a.png)
comment two lines of code as below,
![snip_20161025111532](https://cloud.githubusercontent.com/assets/10937464/19671852/5e2d5c96-9aa4-11e6-8ce2-71b8315f7532.png)
rebuild File Server test suite, and see what will happen?
@JessieF is working on the other bug. 

Thanks,
Yan

**Comment by JessieF** [comment]
Hi Shishir,

Thanks for your quick response!
From the trace, PTM crash probably caused by the multithread. Since I haven't found a way to repro it, could you help to try this quick fix? 

Add a locking object for Method '_**public void ChangeStatus(string testCaseName, TestCaseStatus status)**_'  in '_ProtocolTestManager\Kernel\TestEngine\GroupByOutcome.cs_', as below,

![image](https://cloud.githubusercontent.com/assets/15863655/19673795/bb913e14-9ab5-11e6-9825-0b987b7ff3ba.png)

BTW, could you share the repro steps? Thank you.

/Jessie

**Comment by shishir-compuverde** [comment]
@yazeng  
I’ve applied your proposed solution but still we have crash in QTAgent. Please have a look on the attached screenshot for details.

![qtagent crash1](https://cloud.githubusercontent.com/assets/22982616/19687042/2b7e9254-9ac4-11e6-850c-f303b273c939.PNG)
![qtagent crash1_vs](https://cloud.githubusercontent.com/assets/22982616/19687049/33e4260c-9ac4-11e6-9731-e2338720ab2a.PNG)

**System.TimeoutException was unhandled**
  HResult=-2146233083
  Message=The operation has timed out.
  Source=Microsoft.Protocols.TestTools.StackSdk.FileAccessService.Smb2

  **_StackTrace:_**
       at Microsoft.Protocols.TestTools.StackSdk.FileAccessService.Smb2.ReceivedPackets.WaitPacket(UInt64 messageId)
       at Microsoft.Protocols.TestTools.StackSdk.FileAccessService.Smb2.Smb2Client.ExpectPacket[T](UInt64 messageId)
       at Microsoft.Protocols.TestTools.StackSdk.FileAccessService.Smb2.Smb2Client.SendPacketAndExpectResponse[T](Smb2Packet packet)
       at Microsoft.Protocols.TestTools.StackSdk.FileAccessService.Smb2.Smb2Client.TreeDisconnect(UInt16 creditCharge, UInt16 creditRequest, Packet_Header_Flags_Values flags, UInt64 messageId, UInt64 sessionId, UInt32 treeId, Packet_Header& responseHeader, TREE_DISCONNECT_Response& responsePayload, UInt16 channelSequence)
       at Microsoft.Protocols.TestSuites.FileSharing.FSA.Adapter.Smb2TransportAdapter.TreeDisconnect()
       at Microsoft.Protocols.TestSuites.FileSharing.FSA.Adapter.Smb2TransportAdapter.Dispose(Boolean disposing)
       at Microsoft.Protocols.TestTools.ManagedAdapterBase.Finalize()
  InnerException:


@JessieF 
Here’re the steps that I followed to repro PTM crash -   

_In Protocol Test Manager_
1. Select Test Suite - Click on ‘Configure Wizard’ link
2. Test Suite Introduction - Click on ‘Next’ button
3. Configure Method - Click on ‘Do Manual Configuration’
4. Filter Test Cases - Click on Priority (Select All), Feature (Select All)
5. Configure Test Cases - Set all SUT specific configuration values
6. Configure Adapter - Default
7. Run Selected Test Cases – Select Group by Outcome, select all test cases and then click on ‘Run Selected Test’ link

I’ve applied ‘Fix 1’ and it didn’t work. Then I went for the ‘Fix 2’ and I didn’t experience any PTM crash. I couldn’t complete the test run since I got QTAgent crash. I don’t see the result summary in PTM since I’ve applied ‘Fix 2’. 

![result summary](https://cloud.githubusercontent.com/assets/22982616/19687289/208002ec-9ac5-11e6-8da5-22234a075094.PNG)


Thanks a lot to you all for your prompt response.
/Shishir

**Comment by yazeng** [comment]
Hi Shishir,
I think the fix was not applied.
After you rebuilt the test suite, did you reinstall it again? Sorry I forgot to mention it yesterday.

Yan

**Comment by JessieF** [comment]
Hi Shishir, 

When a QTAgent crashed, you could close the console, then the PTM will auto launch a new console to continue the test.

Then I have three questions, 

- You said "I don’t see the result summary in PTM since I’ve applied ‘Fix 2’.", what do mean by that?

- If you close the crashed console to continue the test, what will happen in your environment?

- If you escape these cases caused QTAgent crash, could you repro the PTM crash?

Thanks a lot for your help. 
/Jessie

**Comment by shishir-compuverde** [comment]
Hi Yan,
I’ve reinstalled the File server test suite. However, I got QTAgent crash in a different place now. It stopped with error -
![qtagent crash1](https://cloud.githubusercontent.com/assets/22982616/19730108/6f648cfa-9b99-11e6-90e5-0ed0cc9bf5e0.PNG)

2016-10-26 14:36:20.906 [Comment] This case is designed to test whether server can handle file deletion request when Treeconnect.MaximalAccess does not include DELETE or GENERIC_ALL.
2016-10-26 14:36:20.906 [Debug] Test whether the specific share exists: \\ts2node01\AzShare
2016-10-26 14:36:20.906 [CheckSucceeded] Assert.IsTrue succeeded. serverIp should not be empty when transport type is TCP.
2016-10-26 14:36:20.906 [Debug] Connect to server 192.168.12.173 over TCP
2016-10-26 14:36:20.921 [Debug] Client sends NEGOTIATE message.
2016-10-26 14:36:20.921 [Debug] Microsoft.Protocols.TestTools.StackSdk.FileAccessService.Smb2.SmbNegotiateRequestPacket
2016-10-26 14:36:20.921 [Debug] R NEGOTIATE, Dialect=Smb2Wildcard, Capabilities=GLOBAL_CAP_DFS, GLOBAL_CAP_LEASING, GLOBAL_CAP_LARGE_MTU
2016-10-26 14:36:20.921 [CheckSucceeded] Assert.AreEqual succeeded. ComNegotiate should succeed.
2016-10-26 14:36:20.921 [Debug] The selected dialect is Smb2Wildcard
2016-10-26 14:36:20.921 [Debug] C NEGOTIATE, Dialects={Smb2002,Smb21,Smb30,Smb302,Smb311}, HashAlgorithms={SHA_512}, Ciphers={ENCRYPTION_AES128_GCM,ENCRYPTION_AES128_CCM}, Capabilities=GLOBAL_CAP_DFS, GLOBAL_CAP_LEASING, GLOBAL_CAP_LARGE_MTU, GLOBAL_CAP_MULTI_CHANNEL, GLOBAL_CAP_PERSISTENT_HANDLES, GLOBAL_CAP_DIRECTORY_LEASING, GLOBAL_CAP_ENCRYPTION
2016-10-26 14:36:20.937 [Debug] R NEGOTIATE, Dialect=Smb311, HashAlgorithms={SHA_512}, Ciphers={ENCRYPTION_AES128_GCM}, Capabilities=GLOBAL_CAP_DFS, GLOBAL_CAP_LEASING, GLOBAL_CAP_LARGE_MTU, GLOBAL_CAP_MULTI_CHANNEL, GLOBAL_CAP_PERSISTENT_HANDLES, GLOBAL_CAP_DIRECTORY_LEASING
2016-10-26 14:36:20.937 [Debug] Client sends SESSION_SETUP message using account: Administrator@testsuite2.local.
2016-10-26 14:36:20.953 [Debug] C SESSION_SETUP, SecurityMode=NEGOTIATE_SIGNING_ENABLED, Capabilities=GLOBAL_CAP_DFS
2016-10-26 14:36:20.953 [Debug] R SESSION_SETUP, SessionFlags=NONE, SessionId=2370548076122001
2016-10-26 14:36:20.953 [Debug] Client sends TREE_CONNECT message to access share: \\ts2node01\AzShare.
2016-10-26 14:36:20.953 [Debug] C TREE CONNECT, Path=\\ts2node01\AzShare
2016-10-26 14:36:20.968 [Debug] R TREE CONNECT, TreeId=0x1
2016-10-26 14:36:20.968 [Debug] Share exists: \\ts2node01\AzShare
2016-10-26 14:36:20.968 [Debug] C TREE DISCONNECT, TreeId=0x1
2016-10-26 14:36:20.968 [Debug] R TREE DISCONNECT
2016-10-26 14:36:20.968 [Debug] C LOGOFF, SessionId=2370548076122001
2016-10-26 14:36:21.000 [Debug] R LOGOFF
2016-10-26 14:36:21.000 [TestStep] Configurable share exists: \\ts2node01\AzShare. MS-SRVS protocol will be used to set share permissions.
2016-10-26 14:36:21.250 [TestStep] Set Security Descriptor on the share (\\ts2node01\AzShare): O:S-1-5-21-1285895573-949531537-4082356298-500G:DUD:(A;;0x1effff;;;S-1-5-21-1285895573-949531537-4082356298-1109)(A;OICI;FA;;;WD)(A;OICI;FA;;;BA).
2016-10-26 14:36:21.437 [CheckSucceeded] Assert.IsTrue succeeded. serverIp should not be empty when transport type is TCP.
2016-10-26 14:36:21.437 [Debug] Connect to server 192.168.12.173 over TCP
2016-10-26 14:36:21.437 [Debug] Client sends NEGOTIATE message.
2016-10-26 14:36:21.437 [Debug] Microsoft.Protocols.TestTools.StackSdk.FileAccessService.Smb2.SmbNegotiateRequestPacket
2016-10-26 14:36:21.437 [Debug] R NEGOTIATE, Dialect=Smb2Wildcard, Capabilities=GLOBAL_CAP_DFS, GLOBAL_CAP_LEASING, GLOBAL_CAP_LARGE_MTU
2016-10-26 14:36:21.437 [CheckSucceeded] Assert.AreEqual succeeded. ComNegotiate should succeed.
2016-10-26 14:36:21.453 [Debug] The selected dialect is Smb2Wildcard
2016-10-26 14:36:21.453 [Debug] C NEGOTIATE, Dialects={Smb2002,Smb21,Smb30,Smb302,Smb311}, HashAlgorithms={SHA_512}, Ciphers={ENCRYPTION_AES128_GCM,ENCRYPTION_AES128_CCM}, Capabilities=GLOBAL_CAP_DFS, GLOBAL_CAP_LEASING, GLOBAL_CAP_LARGE_MTU, GLOBAL_CAP_MULTI_CHANNEL, GLOBAL_CAP_PERSISTENT_HANDLES, GLOBAL_CAP_DIRECTORY_LEASING, GLOBAL_CAP_ENCRYPTION
2016-10-26 14:36:21.468 [Debug] R NEGOTIATE, Dialect=Smb311, HashAlgorithms={SHA_512}, Ciphers={ENCRYPTION_AES128_GCM}, Capabilities=GLOBAL_CAP_DFS, GLOBAL_CAP_LEASING, GLOBAL_CAP_LARGE_MTU, GLOBAL_CAP_MULTI_CHANNEL, GLOBAL_CAP_PERSISTENT_HANDLES, GLOBAL_CAP_DIRECTORY_LEASING
2016-10-26 14:36:21.468 [Debug] Client sends SESSION_SETUP message using account: AzUser01@testsuite2.local.
2016-10-26 14:36:21.468 [Debug] C SESSION_SETUP, SecurityMode=NEGOTIATE_SIGNING_ENABLED, Capabilities=GLOBAL_CAP_DFS
2016-10-26 14:36:21.484 [Debug] R SESSION_SETUP, SessionFlags=NONE, SessionId=2370548076120469
2016-10-26 14:36:21.484 [Debug] Client sends TREE_CONNECT message to access share: \\ts2node01\AzShare.
2016-10-26 14:36:21.484 [Debug] C TREE CONNECT, Path=\\ts2node01\AzShare
2016-10-26 14:36:21.500 [Debug] R TREE CONNECT, TreeId=0x1
2016-10-26 14:36:21.500 [CheckFailed] Assert.IsTrue failed. Treeconnect.MaximalAccess does not include DELETE or GENERIC_ALL.
2016-10-26 14:36:21.500 [Comment]    at Microsoft.Protocols.TestSuites.FileSharing.Auth.TestSuite.SharePermissionTest.<SharePermission_CreateClose_DeleteFile_MaximalAccessNotIncludeDeleteOrGenericAll>b__0(Packet_Header header, TREE_CONNECT_Response response) in c:\Users\administrator.TESTSUITE2\Desktop\Softwares\WindowsProtocolTestSuites-staging\TestSuites\FileServer\src\Auth\TestSuite\Authorization\SharePermissionTest.cs:line 253

2016-10-26 14:36:21.500 [CheckFailed] Assert.Fail failed. Case failed due to: Assert.IsTrue failed. Treeconnect.MaximalAccess does not include DELETE or GENERIC_ALL.
===== Stack Trace =====
   at Microsoft.Protocols.TestSuites.FileSharing.Auth.TestSuite.SharePermissionTest.<SharePermission_CreateClose_DeleteFile_MaximalAccessNotIncludeDeleteOrGenericAll>b__0(Packet_Header header, TREE_CONNECT_Response response) in c:\Users\administrator.TESTSUITE2\Desktop\Softwares\WindowsProtocolTestSuites-staging\TestSuites\FileServer\src\Auth\TestSuite\Authorization\SharePermissionTest.cs:line 253
=== End of Stack Trace ===

2016-10-26 14:36:21.500 [Comment]    at Microsoft.Protocols.TestSuites.FileSharing.Auth.TestSuite.SharePermissionTest.SharePermission_CreateClose_DeleteFile_MaximalAccessNotIncludeDeleteOrGenericAll() in c:\Users\administrator.TESTSUITE2\Desktop\Softwares\WindowsProtocolTestSuites-staging\TestSuites\FileServer\src\Auth\TestSuite\Authorization\SharePermissionTest.cs:line 251

2016-10-26 14:36:21.718 [TestFailed] Microsoft.Protocols.TestSuites.FileSharing.Auth.TestSuite.SharePermissionTest.SharePermission_CreateClose_DeleteFile_MaximalAccessNotIncludeDeleteOrGenericAll
2016-10-26 14:36:21.828 [Comment] Actual time taken for the test suite execution (in seconds) is: 1091,0021104
2016-10-26 14:36:22.343 [Comment] Actual time taken for the test suite execution (in seconds) is: 369,1257457
2016-10-26 14:36:22.359 [Comment] Actual time taken for the test suite execution (in seconds) is: 125,9690066
2016-10-26 14:36:22.375 [Comment] Actual time taken for the test suite execution (in seconds) is: 105,8127001
2016-10-26 14:36:22.390 [Comment] Actual time taken for the test suite execution (in seconds) is: 104,093951
2016-10-26 14:36:22.437 [Comment] Actual time taken for the test suite execution (in seconds) is: 60,1407565
2016-10-26 14:36:22.468 [Comment] Actual time taken for the test suite execution (in seconds) is: 7,1406408
2016-10-26 14:36:22.468 [Comment] begin output test statistics.
2016-10-26 14:36:22.468 [Comment] PTFTestResult.TestsExecuted: 45
2016-10-26 14:36:22.484 [Comment] PTFTestResult.TestsFailed: 28
2016-10-26 14:36:22.484 [Comment] PTFTestResult.TestsPassed: 17

Unhandled Exception: System.ObjectDisposedException: Cannot access a closed pipe.
   at System.IO.__Error.PipeNotOpen()
   at System.IO.Pipes.PipeStream.CheckWriteOperations()
   at System.IO.Pipes.PipeStream.Flush()
   at System.IO.StreamWriter.Flush(Boolean flushStream, Boolean flushEncoder)
   at System.IO.StreamWriter.Dispose(Boolean disposing)
   at System.IO.StreamWriter.Close()
   at Microsoft.Protocols.TestTools.Logging.PipeSink.Dispose(Boolean disposing)
   at Microsoft.Protocols.TestTools.Logging.LogSink.Finalize()



I pressed the ‘Debug’ button on error message, but it continued to run the test instead of stopping in VS. Later I encountered the following error
![qtagent crash2](https://cloud.githubusercontent.com/assets/22982616/19730371/4b7d8f02-9b9a-11e6-8740-8c6c1ada549a.PNG)

**System.NullReferenceException was unhandled**
  HResult=-2147467261
  Message=Object reference not set to an instance of an object.
  Source=MS-SMB2_ServerTestSuite
  _**StackTrace:**_
       at Microsoft.Protocols.TestSuites.FileSharing.SMB2.TestSuite.SMB2TestBase.CheckBreakNotification(Object obj) in c:\Users\administrator.TESTSUITE2\Desktop\Softwares\WindowsProtocolTestSuites-staging\TestSuites\FileServer\src\SMB2\TestSuite\Leasing\SMB2LeasingTestBase.cs:line 118
       at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.TimerQueueTimer.CallCallback()
       at System.Threading.TimerQueueTimer.Fire()
       at System.Threading.TimerQueue.FireNextTimers()

Thank you so much for your help.
/Shishir

**Comment by JessieF** [comment]
Hi Shishir,

For the first exception, you could comment a line in PTM to avoid it.
![image](https://cloud.githubusercontent.com/assets/15863655/19757984/9c2e23b2-9c58-11e6-8721-a37fd814bb6c.png)

Quick Fix: Comment this line in 'ProtocolTestManager\Kernel\TestEngine\PipeSinkServer.cs', then build a new PTM and install it.
![image](https://cloud.githubusercontent.com/assets/15863655/19758037/edea3a56-9c58-11e6-9393-14d7c1ca4ecb.png)

By the way, this exception is thrown by PTF, we will fix this issue later. Hope it will not block your test.
Thanks a lot for your help.
/Jessie

**Comment by shishir-compuverde** [comment]
Hi Jessie,
I escape the cases caused PTF exception. PTM is working fine now.
Thanks a lot for your good work.

/Shishir

**Comment by shishir-compuverde** [comment]
Hi Jessie,
Forgot to mention one thing. I was wondering how big of an effort is fixing the PTF exception for you guys.

The reason I am asking is because we are including the test suite results in our marketing materials, which are due for publication quite soon (1-2 days). Since it is not really possible for us to use incomplete results (with exceptions), I am wondering if having that issue fixed any time soon is a realistic expectation. However, if the fix requires a longer time, could you consider excluding the test cases that cause the exception from the Git-repository until they are fixed? I am thinking that for now this could be a valid solution for other users too, if anyone else runs into the same problem.

Please let me know what you think.

Thanks,
/Shishir

**Comment by yazeng** [comment]
Hi Shishir,
Did you apply the quick fix (Comment this line in 'ProtocolTestManager\Kernel\TestEngine\PipeSinkServer.cs')?
We believe the quick fix should solve the exception below:
    **Unhandled Exception: System.ObjectDisposedException: Cannot access a closed pipe.**
The bug in PTF which Jessie mentioned is also related to this issue. Which means it's better that we modify PTF to fix this issue, but it can also work if you apply the quick fix, aka the work around. So whether we change PTF or not should not block your test.

The issue (**System.NullReferenceException was unhandled**) is another one. What's the impact of this issue? Does it cause QTAgent crash? Can you tell which variable is null?

Thanks,
Yan

**Comment by shishir-compuverde** [comment]
Hi Yan,
I applied the quick fix in PipeSinkServer.cs, but still we have QTAgent crash due to the issue (System.NullReferenceException was unhandled).

![qtagent crash1](https://cloud.githubusercontent.com/assets/22982616/19802872/1af35d18-9d06-11e6-866d-69c8c298d38d.PNG)

**System.NullReferenceException was unhandled**
  HResult=-2147467261
  Message=Object reference not set to an instance of an object.
  Source=MS-SMB2_ServerTestSuite
  StackTrace:
       at Microsoft.Protocols.TestSuites.FileSharing.SMB2.TestSuite.SMB2TestBase.CheckBreakNotification(Object obj) in c:\Users\administrator.TESTSUITE2\Desktop\Softwares\WindowsProtocolTestSuites-staging\TestSuites\FileServer\src\SMB2\TestSuite\Leasing\SMB2LeasingTestBase.cs:line 118
       at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.TimerQueueTimer.CallCallback()
       at System.Threading.TimerQueueTimer.Fire()
       at System.Threading.TimerQueue.FireNextTimers()
  InnerException: 

Thanks,
/Shishir

**Comment by yazeng** [comment]
Hi Shishir,
Could you replace this line "TestConfig.WaitTimeoutInMilliseconds" to "5000", rebuild it, reinstall it and try again?
![snip_20161031152423](https://cloud.githubusercontent.com/assets/10937464/19846942/217e36ba-9f7e-11e6-81b5-6ec06c8de580.png)

**Comment by shishir-compuverde** [comment]
Hi Yan,
Everything is working well now without any crash.

Thanks a lot for your effort.
/Shishir

**Comment by yazeng** [comment]
Glad to here that.
You also helped us a lot! We could never find those bugs by ourselves.
BTW, the solution I gave you is just a remedy. I already filed bugs in our systems and will make the fix and update code in GitHub.

**Comment by chenlu0616** [comment]
Close since it works now.
